Instructions/10992A_LAB_AK_04.md
Start the Backup Infrastructure option from the Manage section instead of settings
=> Backup Vault Manage section

Instructions/10992A_LAB_AK_01.md
Added confirm password and managed disks option
=> Added confirm password and managed disks option

Instructions/10992A_LAB_AK_03.md
Replaced a few less than greater than characters in xml format
=> Less greater than

Instructions/10992A_LAB_AK_04.md
Protected servers instead of Production servers
=> Protected servers

Instructions/10992A_LAB_AK_05.md
Post-failover resource group option was missing.
AdatumASRRG
=> Post-failover resource group

Instructions/10992A_LAB_AK_06.md
=> Added managed disks

Instructions/10992A_LAB_AK_06.md
Replaced less than greater than tags with the correct symbols
=> Replaced less than greater than

Instructions/10992A_LAB_02.md
(Stray change at line 188, please reject that change)
=> Kitematic (not Kinematic) typo

Instructions/10992A_LAB_AK_04.md
Now you must click on the name of the server to open the server's blade, then click "Delete"
(I seem to have inserted a stray space at line 101, please reject it)
=> Delete server moved from the context menu

Instructions/10992A_LAB_AK_05.md
Has planning be done? was moved to earlier in the sequence and delete options changed in several locations. In addition, you can't scroll back to the ASRVault blade, it needs to be re-opened.
On the planning question, either "Yes, I have done it" or "I will do it later" will allow the student to proceed, if "Yes, I have done it" is preferred, please change it back.
Also, a couple of stray spaces removed.
=> Interface changes

Instructions/10992A_LAB_AK_01.md
So that the **Select a deployment model** option is shown.
=> Changed create VM steps

Instructions/10992A_LAB_AK_02.md
and bolded **Run as Administrator**
=> Storage Account type change

Instructions/10992A_LAB_AK_06.md
Not sure why the notes are different in this file, that big section in EX 1, Task 4 is showing edited, when I was trying to clean up the note at step 7.
=> Added missing escape characters; misc typos

Instructions/10992A_LAB_AK_06.md
=> fixed note formatting

Instructions/10992A_LAB_AK_03.md
=> Added escape characters

Instructions/10992A_LAB_AK_04.md
=> add escape characters

Instructions/10992A_LAB_01.md, Instructions/10992A_LAB_02.md, Instructions/10992A_LAB_03.md, Instructions/10992A_LAB_04.md, Instructions/10992A_LAB_05.md, Instructions/10992A_LAB_06.md, Instructions/10992A_LAB_07.md, Instructions/10992A_LAB_AK_01.md, Instructions/10992A_LAB_AK_02.md, Instructions/10992A_LAB_AK_03.md, Instructions/10992A_LAB_AK_04.md, Instructions/10992A_LAB_AK_05.md, Instructions/10992A_LAB_AK_06.md, Instructions/10992A_LAB_AK_07.md
plus: added sign in to Visual Studio in Lab 01, re-did verify restore steps in Lab 04, changed all of the "use closest Azure region" to "use Azure region specified by instructor"
=> Pandoc formatting changes

Build/README.md, Instructions/10992B_LAB_AK_01.md, Instructions/10992B_LAB_AK_02.md, Instructions/10992B_LAB_AK_03.md, Instructions/10992B_LAB_AK_04.md, Instructions/10992B_LAB_AK_05.md, Instructions/10992B_LAB_AK_06.md, Instructions/10992B_LAB_AK_07.md
"+New" is now "+Create a resource", "More services" is now "All
services", corrected Pandoc URL in Readme.
=> New and More Changed in Azure

Instructions/10992B_LAB_AK_01.md
When adding a VM in the portal, there is a new item for Backup and you can no longer uncheck add tile to Dashboard. Added steps to clean up the Dashboard at the end of lab.
=> Adding a VM changed in portal

Instructions/10992B_LAB_AK_03.md, Instructions/10992B_LAB_AK_04.md
In editing, the creation of the certificates was simplified by using PowerShell, however, this means that the Certificates mmc is not open when Ex 1, Task 3 starts. Added instructions to open the mmc and add Certificates snap-in.
=> Update 10992B_LAB_AK_03.md: Cert snap-in needed

Instructions/10992B_LAB_AK_01.md, Instructions/10992B_LAB_AK_06.md
Also, the label for the Public IP address of a VM changed.
=> VM tab "Guest config" is now "Advanced"
